window.CHEONGRYEOM_CONTENT = {
  program: {
    title: "청렴, 자격이 되다 3.0",
    subtitle: "청렴직무능력검정 – 아는 청렴에서 해내는 청렴으로",
    totalMinutes: 47,
    model: "한국산업인력공단 자격검정 모티브",
  },
  virtues: [
    { key: "honesty", name: "정직", tag: "사실을 밝히는 힘", desc: "사실과 근거를 숨기거나 꾸미지 않고 투명하게 설명하는 역량", feedback: "정보의 출처와 나의 이해관계를 먼저 밝히는 연습을 해보세요." },
    { key: "promise", name: "약속", tag: "기준을 지키는 힘", desc: "공동체가 합의한 규칙과 절차를 상황에 따라 바꾸지 않는 역량", feedback: "결정 전에 규칙을 확인하고, 예외가 필요하면 모두에게 공개하세요." },
    { key: "care", name: "배려", tag: "영향을 살피는 힘", desc: "친한 사람뿐 아니라 결정의 영향을 받는 모두의 권리를 살피는 역량", feedback: "내 선택에서 소외되거나 불리해질 사람은 없는지 한 번 더 질문하세요." },
    { key: "responsibility", name: "책임", tag: "과정을 완수하는 힘", desc: "맡은 일을 끝까지 수행하고 선택의 과정과 결과를 설명하는 역량", feedback: "문제가 생겼을 때 숨기지 말고 현재 상황과 해결 계획을 함께 공유하세요." },
    { key: "restraint", name: "절제", tag: "사익을 조절하는 힘", desc: "공동의 자원과 권한을 사적인 이익과 분명히 구분하는 역량", feedback: "작은 선물이나 남은 물품도 개인 것이 아니라는 원칙부터 적용하세요." },
    { key: "fairness", name: "공정", tag: "같은 기준을 세우는 힘", desc: "친분과 편견 대신 공개된 기준을 누구에게나 일관되게 적용하는 역량", feedback: "사람을 보기 전에 기준을 먼저 만들고, 같은 자료로 비교해보세요." },
  ],
  stages: [
    { key: "waiting", step: "입실", name: "수험등록·검정안내", short: "수험등록", duration: 3 },
    { key: "written", step: "STEP 1", name: "필기시험 · 청렴판단", short: "필기시험", duration: 10 },
    { key: "practical", step: "STEP 2", name: "실기시험 · 투명업무", short: "실기시험", duration: 14 },
    { key: "team", step: "STEP 3", name: "조별과제 · 합동감사", short: "조별과제", duration: 15 },
    { key: "result", step: "FINAL", name: "종합판정·자격취득", short: "자격취득", duration: 5 },
  ],
  intro: {
    title: "청렴은 외운 정답이 아니라, 기준을 세우고 끝까지 수행하는 직무역량입니다.",
    body: "필기시험에서 판단 기준을 확인하고, 실기시험에서 실제 업무 절차를 수행한 뒤, 조별과제에서 흩어진 증거를 모아 합동감사를 완성합니다. 각 시험 뒤 100점 성적표와 개인별 강점·보완점이 제공됩니다.",
  },
  writtenSeconds: 12,
  written: [
    {
      id: "w1", virtue: "honesty",
      q: "생성형 AI로 수행평가 초안을 만들었다. 제출 전 가장 먼저 해야 할 행동은?",
      options: ["표현만 조금 바꿔 내 글처럼 제출한다.", "학교 지침을 확인하고 사용 범위를 밝힌 뒤 내 생각과 검토를 더한다.", "친구들도 썼다면 별도 확인 없이 제출한다.", "AI가 만든 문장을 모두 삭제하고 처음부터 다시 쓴다."],
      correct: 1,
      ex: "도구 사용 여부만이 아니라 사용 사실과 범위를 투명하게 밝히고, 결과에 책임지는지가 핵심입니다.",
      impact: { honesty: 100, responsibility: 70 },
    },
    {
      id: "w2", virtue: "responsibility",
      q: "내가 맡은 모둠 자료가 늦어져 발표 준비에 차질이 예상된다. 가장 책임 있는 대응은?",
      options: ["늦어진 이유와 현재 상황을 즉시 공유하고 완료 계획이나 대안을 제시한다.", "문제가 커질 때까지 말하지 않고 혼자 해결한다.", "인터넷 자료를 그대로 복사해 기한만 맞춘다.", "다른 모둠원의 역할이 더 쉬웠다고 항의한다."],
      correct: 0,
      ex: "책임은 실수를 숨기지 않고 진행 상황을 공개하며 해결 과정까지 맡는 태도입니다.",
      impact: { responsibility: 100, honesty: 65, promise: 55 },
    },
    {
      id: "w3", virtue: "honesty",
      q: "단체 채팅방에 ‘시험 범위’라는 미확인 정보가 퍼졌다. 가장 청렴한 행동은?",
      options: ["여러 명이 전달했으므로 그대로 재전송한다.", "틀릴 수도 있다고 덧붙여 공유한다.", "출처를 확인하고, 확인되지 않았다면 전달을 멈춘다.", "나만 알고 친구들에게는 말하지 않는다."],
      correct: 2,
      ex: "온라인에서도 사실을 확인하고 잘못된 정보의 확산을 멈추는 것은 정직과 책임의 실천입니다.",
      impact: { honesty: 100, responsibility: 70, care: 50 },
    },
    {
      id: "w4", virtue: "restraint",
      q: "학교 행사 준비비로 산 물품이 남았다. 개인적으로 갖고 싶은 물건이 있다면?",
      options: ["공동 물품 처리 기준을 확인하고 승인된 방식으로 처리한다.", "금액이 작으면 기여한 학생이 가져간다.", "친한 친구끼리 합의해 나누어 갖는다.", "아무도 모르게 창고에 보관한다."],
      correct: 0,
      ex: "공동 자원은 금액이나 친분이 아니라 미리 정한 기준과 승인 절차에 따라 처리해야 합니다.",
      impact: { restraint: 100, promise: 70, responsibility: 55 },
    },
    {
      id: "w5", virtue: "fairness",
      q: "학생회 지원자 중 친한 친구가 있다. 가장 공정한 선발 방식은?",
      options: ["오해를 피하려고 친구에게 무조건 낮은 점수를 준다.", "평소 성격이 좋으므로 조금 높은 점수를 준다.", "평가기준을 먼저 공개하고 모든 지원자에게 같은 기준을 적용한다.", "지원자끼리 서로 점수를 주게 한다."],
      correct: 2,
      ex: "공정은 친한 사람을 무조건 배제하는 것이 아니라, 공개된 기준을 일관되게 적용하는 것입니다.",
      impact: { fairness: 100, honesty: 45, promise: 55 },
    },
    {
      id: "w6", virtue: "care",
      q: "학교 공용 태블릿 이용시간을 정할 때 가장 청렴한 기준은?",
      options: ["먼저 신청한 사람에게 제한 없이 배정한다.", "성적이 높은 학생에게 우선 배정한다.", "필요도·이용목적·대체수단을 공개 기준으로 정하고 이의신청 기회를 둔다.", "담당 선생님이 아는 학생에게 먼저 배정한다."],
      correct: 2,
      ex: "공정한 배분은 모두의 상황을 살피는 기준과, 결정에 질문할 수 있는 절차를 함께 갖춰야 합니다.",
      impact: { care: 100, fairness: 90, promise: 45 },
    },
  ],
  practical: [
    {
      id: "p1", type: "sequence", title: "작업 1 · 투명구매 절차 복원",
      brief: "축제 부스 물품을 구매해야 합니다. 뒤섞인 업무카드를 가장 투명한 순서로 재배치하세요.", points: 35,
      cards: ["이해관계가 있는 사람이 있는지 먼저 공개한다.", "가격·품질·납기 평가기준을 사전에 정한다.", "여러 판매처를 같은 자료와 기준으로 비교한다.", "선정 사유·영수증·잔액 처리 결과를 공개한다."],
      correctOrder: [0, 1, 2, 3], impact: { promise: 95, responsibility: 90, fairness: 85 },
      feedback: "이해관계 공개 → 기준 설정 → 비교·선정 → 기록 공개가 투명업무의 기본 흐름입니다.",
    },
    {
      id: "p2", type: "weights", title: "작업 2 · 공정한 평가기준 설계",
      brief: "업체를 비교할 100점 기준표를 직접 설계하세요. 친분은 평가기준이 될 수 없습니다.", points: 30,
      criteria: [{ key: "price", label: "가격", target: 30 }, { key: "quality", label: "품질·안전", target: 40 }, { key: "delivery", label: "납기·A/S", target: 30 }, { key: "relationship", label: "친분", target: 0 }],
      tolerance: 10, impact: { fairness: 100, care: 70, restraint: 65 },
      feedback: "가격만 보거나 친분을 반영하지 않고, 품질과 이행가능성까지 설명 가능한 기준으로 구성해야 합니다.",
    },
    {
      id: "p3", type: "audit", title: "작업 3 · 전자정산서 오류 탐지",
      brief: "감사 모드로 전환되었습니다. 기록 6개 중 청렴 위험신호 3개를 찾아 표시하세요.", points: 35,
      records: [
        { title: "견적 비교", body: "A·B·C업체의 가격·품질·납기를 같은 양식으로 비교함", risk: false },
        { title: "이해관계", body: "선정 담당자의 친척이 C업체를 운영하지만 회의록에는 기록하지 않음", risk: true },
        { title: "계약 금액", body: "승인된 예산 안에서 계약하고 납품 수량을 확인함", risk: false },
        { title: "개인 쿠폰", body: "업체가 담당 학생 네 명에게만 쿠폰을 제공하고 비공개를 요청함", risk: true },
        { title: "잔액 처리", body: "남은 22,000원으로 담당 학생들만 음료를 구매함", risk: true },
        { title: "결과 공개", body: "선정 사유와 전체 영수증을 학급 게시판에 공개함", risk: false },
      ],
      required: 3, impact: { honesty: 90, restraint: 100, responsibility: 80 },
      feedback: "이해관계 은폐, 개인 혜택, 공동예산의 사적 사용은 금액과 무관하게 확인해야 할 위험신호입니다.",
    },
  ],
  teamMission: {
    id: "t1", title: "사건파일 CR-47 · 응원용품 공동구매",
    brief: "4인 1조로 편성됩니다. 각자 다른 비밀 증거를 감식한 뒤 구두로 브리핑하고, 모든 증거를 합쳐 판정과 재발방지 프로토콜을 완성하세요.",
    roles: [
      { name: "이해관계 확인관", icon: "관계", evidence: "회장이 평가기준을 정하기 전 ‘아는 선배 가족이 운영하는 C업체’를 추천했습니다. 이 관계는 회의록에 없습니다.", correctRisk: "honesty" },
      { name: "기준설계 검증관", icon: "기준", evidence: "A업체 278,000원, B업체 253,000원, C업체 262,000원입니다. C업체가 선정됐지만 품질·납기 점수와 선정 사유가 비어 있습니다.", correctRisk: "fairness" },
      { name: "혜택추적 조사관", icon: "혜택", evidence: "C업체가 담당 학생 네 명에게만 개인 쿠폰을 주겠다고 했고, 한 학생이 ‘우리끼리만 알자’고 답했습니다.", correctRisk: "restraint" },
      { name: "정산기록 감사관", icon: "정산", evidence: "남은 예산 22,000원으로 담당 학생들만 음료를 샀습니다. 반 전체 승인과 잔액 처리 기록은 없습니다.", correctRisk: "responsibility" },
    ],
    tasks: [
      { id: "inspect", title: "1교시 · 비밀증거 감식", instruction: "내 역할에 배정된 증거만 읽고 핵심 위험역량을 판정한 뒤, 모둠원에게 말로 전달할 브리핑을 작성하세요.", points: 25, minLength: 18 },
      { id: "hearing", title: "2교시 · 합동심리", instruction: "모둠원의 구두 브리핑을 들은 뒤, 네 증거를 위험도가 큰 순서로 배치하고 사건을 판정하세요.", points: 35, verdicts: ["청렴 위험 있음", "추가 확인 필요", "문제 없음"], correctVerdict: 0, correctOrder: [2, 0, 3, 1] },
      { id: "protocol", title: "3교시 · 재발방지 설계", instruction: "모둠이 합의한 예방규칙 3개를 고르고, 학교에서 사용할 ‘한 줄 청렴 프로토콜’을 함께 작성하세요.", points: 40, required: 3, minLength: 24,
        actions: [
          { text: "이해관계를 회의 시작 전에 공개하고 관련자는 평가에서 빠진다.", correct: true },
          { text: "가격·품질·납기 기준을 사전에 공개하고 같은 양식으로 비교한다.", correct: true },
          { text: "선정·정산 기록과 개인 혜택 제안을 모두 남기고 공개한다.", correct: true },
          { text: "논란을 줄이기 위해 언제나 가장 싼 업체만 선정한다.", correct: false },
          { text: "모둠원 과반이 찬성하면 개인 혜택도 받을 수 있다.", correct: false },
          { text: "빠른 결정을 위해 친한 사람이 추천한 업체에 우선권을 준다.", correct: false },
        ] },
    ],
    guide: "정보격차가 있어 휴대폰을 돌려 보여주기보다 각 역할자가 직접 말로 브리핑해야 합니다. 교사는 정답을 주지 말고 ‘어떤 증거와 기준으로 설명할 수 있는가’를 되묻습니다.",
  },
  scoring: { writtenWeight: 30, practicalWeight: 35, teamWeight: 35, passTotal: 60, leaderTotal: 85, leaderPractical: 75, leaderTeam: 75 },
};
